---
# pipeline config
cuad_master_csv_mapping_path: ./config/cuad_master_csv_mapping.csv
cuad_data_base_dir: "../" # path to CUAD_v1 dir

# ocr pipeline
ocr_pipeline:
  # dir basename where the ocr results will be saved
  ocr_output_dir: contract_ocr_results/

  # text detection model to use for OCR
  text_detr_model: db_resnet50

  # text recognition model to use for OCR
  text_recog_model: crnn_vgg16_bn

# toc_matching params
toc_matching:
  # min IoU overlap required to merge OCR output
  ocr_line_merge_iou_threshold: 0.65

  # Design decision to only allow subset match ratios of >= 80/100
  subset_match_threshold: 80

  # Design decision to potentially only match document lines
  # that are at least as long as some percentage of the toc label
  line_len_match_threshold: 0.8

  # Design decision to ensure that the beginning of the matched lines
  # have match ratios of >= 80/100
  beg_line_match_threshold: 80

  # in case of toc labels that span multiple lines
  # ensure the top line is at least mildly relevant
  first_line_match_threshold: 20


# user params for results visualization scripts
visualize_results:
  poppler_path: null
  results_base_dir: ../data/contract_pipeline_results/
  full_contract_image_dir: full_contract_images/
  annotated_image_dir: annotated_images/
  image_dpi: 100
  image_fmt: jpeg

...
