---
# path to the cuad master csv mapping containing all the relevant metadata
# such as paths to pdf, html, etc, contract_uids and original contract names
cuad_master_csv_mapping_path: ./config/cuad_master_csv_mapping.csv

# path to CUAD_v1 dir
cuad_data_base_dir: "../data/"

# dir where the results of the end-to-end pipeline will be stored
pipeline_results_dir: CUAD_v1/contract_pipeline_results/

# html parsing pipeline
html_pipeline:
  processed_html_output_dir: CUAD_v1/contract_processed_html/

# ocr pipeline
ocr_pipeline:
  # dir basename where the ocr results will be saved
  ocr_output_dir: CUAD_v1/contract_ocr_results/

  # text detection model to use for OCR
  text_detr_model: db_resnet50

  # text recognition model to use for OCR
  text_recog_model: crnn_vgg16_bn

  # min IoU overlap required to merge OCR output
  ocr_line_merge_iou_threshold: 0.65

# toc_matching params
toc_matching_pipeline:

  # Design decision to only allow subset match ratios of >= 80/100
  subset_match_threshold: 80

  # Design decision to potentially only match document lines
  # that are at least as long as some percentage of the toc label
  line_len_match_threshold: 0.8

  # Design decision to ensure that the beginning of the matched lines
  # have match ratios of >= 80/100
  beg_line_match_threshold: 80

  # in case of toc labels that span multiple lines
  # ensure the top line is at least mildly relevant
  first_line_match_threshold: 20


# user params for results visualization scripts
visualize_results_pipeline:
  poppler_path: null

  # dir where the images from the pdf2image conversion will be saved
  full_contract_image_dir: CUAD_v1/full_contract_images/

  # dir where the images annotated with bbox will be saved
  annotated_image_dir: CUAD_v1/annotated_images/

  # dir where the input pdf will be saved
  # this will be saved within a the following dir
  # CUAD_v1/contract_pipeline_results/contract_uid
  input_pdf_save_dir: contract_pdf

  # dir where the input html will be saved
  # this will be saved within a the following dir
  # CUAD_v1/contract_pipeline_results/contract_uid
  input_html_save_dir: contract_html

  # the dpi of the images obtained from conversion from pdf
  image_dpi: 100

  # the format that the images obtained from pdf2image conversion will be
  # saved in
  image_fmt: jpeg

...
